### ISSUE TITLE
cpu空转可以上3.9，但是偶尔编译的时候锁0.8

### ISSUE THREAD

**Issue by oreoft** [smallssnow/XPS9570-8570H-macos#6]
已经解锁DPTF和CFG-LOCK，肿么办呀，好烦人，感觉要放弃啦

**Comment by flyingchase** [comment]
求问一下老哥 DPTF在哪里解开啊? 我的bios没有这项设置,能发个图看看不? 
我的是7590 big sur 11.2.2 也是多任务下会出现锁频0.8ghz, 查了一圈说是VRM过热, 打开盖子贴了散热贴还是不行,,,

**Comment by oreoft** [comment]
> 求问一下老哥 DPTF在哪里解开啊? 我的bios没有这项设置,能发个图看看不?
> 我的是7590 big sur 11.2.2 也是多任务下会出现锁频0.8ghz, 查了一圈说是VRM过热, 打开盖子贴了散热贴还是不行,,,

好家伙，我还以为是南桥，vrm啊这咋整啊。dptf需要设置bios偏移量关闭。具体工具和方法在下面
https://github.com/datasone/grub-mod-setup_var

**Comment by flyingchase** [comment]
谢谢老哥 我查到的关于0.8ghz这个issue讨论蛮多的, 可以试试看,
https://github.com/LuletterSoul/Dell-XPS15-9570-macOS/issues/48
https://www.reddit.com/r/Dell/comments/7orxcs/how_to_get_your_xps_15_running_cold/
https://www.reddit.com/r/Dell/comments/cua4jl/dell_xps_7590_where_should_i_place_thermal_pad/

**Comment by oreoft** [comment]
> 谢谢老哥 我查到的关于0.8ghz这个issue讨论蛮多的, 可以试试看,
> [LuletterSoul/Dell-XPS15-9570-macOS#48](https://github.com/LuletterSoul/Dell-XPS15-9570-macOS/issues/48)
> https://www.reddit.com/r/Dell/comments/7orxcs/how_to_get_your_xps_15_running_cold/
> https://www.reddit.com/r/Dell/comments/cua4jl/dell_xps_7590_where_should_i_place_thermal_pad/

**Comment by flyingchase** [comment]
> > 求问一下老哥 DPTF在哪里解开啊? 我的bios没有这项设置,能发个图看看不?
> > 我的是7590 big sur 11.2.2 也是多任务下会出现锁频0.8ghz, 查了一圈说是VRM过热, 打开盖子贴了散热贴还是不行,,,
> 
> 好家伙，我还以为是南桥，vrm啊这咋整啊。dptf需要设置bios偏移量关闭。具体工具和方法在下面
> https://github.com/datasone/grub-mod-setup_var

不好意思打扰老哥 想请问一下 DVMT的偏移量值是多少啊？ 我捣鼓了一下还是 64MB 没改成 96Mb

**Comment by oreoft** [comment]
> > > 求问一下老哥 DPTF在哪里解开啊? 我的bios没有这项设置,能发个图看看不?
> > > 我的是7590 big sur 11.2.2 也是多任务下会出现锁频0.8ghz, 查了一圈说是VRM过热, 打开盖子贴了散热贴还是不行,,,
> > 
> > 
> > 好家伙，我还以为是南桥，vrm啊这咋整啊。dptf需要设置bios偏移量关闭。具体工具和方法在下面
> > https://github.com/datasone/grub-mod-setup_var
> 
> 不好意思打扰老哥 想请问一下 DVMT的偏移量值是多少啊？ 我捣鼓了一下还是 64MB 没改成 96Mb

7590不太清楚，但是我可以帮你问一下，我有朋友是7590

**Comment by oreoft** [comment]
> > > > 求问一下老哥 DPTF在哪里解开啊? 我的bios没有这项设置,能发个图看看不?
> > > > 我的是7590 big sur 11.2.2 也是多任务下会出现锁频0.8ghz, 查了一圈说是VRM过热, 打开盖子贴了散热贴还是不行,,,
> > > 
> > > 
> > > 好家伙，我还以为是南桥，vrm啊这咋整啊。dptf需要设置bios偏移量关闭。具体工具和方法在下面
> > > https://github.com/datasone/grub-mod-setup_var
> > 
> > 
> > 不好意思打扰老哥 想请问一下 DVMT的偏移量值是多少啊？ 我捣鼓了一下还是 64MB 没改成 96Mb
> 
> 7590不太清楚，但是我可以帮你问一下，我有朋友是7590

我上传到网盘了。里面有所有7590的偏移量，希望对你有帮助
https://cloud.189.cn/t/nUnyMra6773e

**Comment by flyingchase** [comment]
> > > > > 求问一下老哥 DPTF在哪里解开啊? 我的bios没有这项设置,能发个图看看不?
> > > > > 我的是7590 big sur 11.2.2 也是多任务下会出现锁频0.8ghz, 查了一圈说是VRM过热, 打开盖子贴了散热贴还是不行,,,
> > > > 
> > > > 
> > > > 好家伙，我还以为是南桥，vrm啊这咋整啊。dptf需要设置bios偏移量关闭。具体工具和方法在下面
> > > > https://github.com/datasone/grub-mod-setup_var
> > > 
> > > 
> > > 不好意思打扰老哥 想请问一下 DVMT的偏移量值是多少啊？ 我捣鼓了一下还是 64MB 没改成 96Mb
> > 
> > 
> > 7590不太清楚，但是我可以帮你问一下，我有朋友是7590
> 
> 我上传到网盘了。里面有所有7590的偏移量，希望对你有帮助
> https://cloud.189.cn/t/nUnyMra6773e

谢谢老哥！修改后 我的7590仍然还是会出现 0.8ghz 降频 醉了 散热也改造了，，，

**Comment by oreoft** [comment]
> > > > > > 求问一下老哥 DPTF在哪里解开啊? 我的bios没有这项设置,能发个图看看不?
> > > > > > 我的是7590 big sur 11.2.2 也是多任务下会出现锁频0.8ghz, 查了一圈说是VRM过热, 打开盖子贴了散热贴还是不行,,,
> > > > > 
> > > > > 
> > > > > 好家伙，我还以为是南桥，vrm啊这咋整啊。dptf需要设置bios偏移量关闭。具体工具和方法在下面
> > > > > https://github.com/datasone/grub-mod-setup_var
> > > > 
> > > > 
> > > > 不好意思打扰老哥 想请问一下 DVMT的偏移量值是多少啊？ 我捣鼓了一下还是 64MB 没改成 96Mb
> > > 
> > > 
> > > 7590不太清楚，但是我可以帮你问一下，我有朋友是7590
> > 
> > 
> > 我上传到网盘了。里面有所有7590的偏移量，希望对你有帮助
> > https://cloud.189.cn/t/nUnyMra6773e
> 
> 谢谢老哥！修改后 我的7590仍然还是会出现 0.8ghz 降频 醉了 散热也改造了，，，

同命相连，但是散热加强以后，锁800mhz貌似好一些，所以感觉和这个还是有点关系，加上现在天气热公司也有空调，很少遇到了。

**Comment by flyingchase** [comment]
> > > > > > > 求问一下老哥 DPTF在哪里解开啊? 我的bios没有这项设置,能发个图看看不?
> > > > > > > 我的是7590 big sur 11.2.2 也是多任务下会出现锁频0.8ghz, 查了一圈说是VRM过热, 打开盖子贴了散热贴还是不行,,,
> > > > > > 
> > > > > > 
> > > > > > 好家伙，我还以为是南桥，vrm啊这咋整啊。dptf需要设置bios偏移量关闭。具体工具和方法在下面
> > > > > > https://github.com/datasone/grub-mod-setup_var
> > > > > 
> > > > > 
> > > > > 不好意思打扰老哥 想请问一下 DVMT的偏移量值是多少啊？ 我捣鼓了一下还是 64MB 没改成 96Mb
> > > > 
> > > > 
> > > > 7590不太清楚，但是我可以帮你问一下，我有朋友是7590
> > > 
> > > 
> > > 我上传到网盘了。里面有所有7590的偏移量，希望对你有帮助
> > > https://cloud.189.cn/t/nUnyMra6773e
> > 
> > 
> > 谢谢老哥！修改后 我的7590仍然还是会出现 0.8ghz 降频 醉了 散热也改造了，，，
> 
> 同命相连，但是散热加强以后，锁800mhz貌似好一些，所以感觉和这个还是有点关系，加上现在天气热公司也有空调，很少遇到了。

我这也是出现次数少了一些，还试过 voltageshift 设置cpu 电压，效果也不是很好。。。将就用了打算，下次换白果。。。

**Comment by oreoft** [comment]
> > > > > > > > 求问一下老哥 DPTF在哪里解开啊? 我的bios没有这项设置,能发个图看看不?
> > > > > > > > 我的是7590 big sur 11.2.2 也是多任务下会出现锁频0.8ghz, 查了一圈说是VRM过热, 打开盖子贴了散热贴还是不行,,,
> > > > > > > 
> > > > > > > 
> > > > > > > 好家伙，我还以为是南桥，vrm啊这咋整啊。dptf需要设置bios偏移量关闭。具体工具和方法在下面
> > > > > > > https://github.com/datasone/grub-mod-setup_var
> > > > > > 
> > > > > > 
> > > > > > 不好意思打扰老哥 想请问一下 DVMT的偏移量值是多少啊？ 我捣鼓了一下还是 64MB 没改成 96Mb
> > > > > 
> > > > > 
> > > > > 7590不太清楚，但是我可以帮你问一下，我有朋友是7590
> > > > 
> > > > 
> > > > 我上传到网盘了。里面有所有7590的偏移量，希望对你有帮助
> > > > https://cloud.189.cn/t/nUnyMra6773e
> > > 
> > > 
> > > 谢谢老哥！修改后 我的7590仍然还是会出现 0.8ghz 降频 醉了 散热也改造了，，，
> > 
> > 
> > 同命相连，但是散热加强以后，锁800mhz貌似好一些，所以感觉和这个还是有点关系，加上现在天气热公司也有空调，很少遇到了。
> 
> 我这也是出现次数少了一些，还试过 voltageshift 设置cpu 电压，效果也不是很好。。。将就用了打算，下次换白果。。。

我也是等换白果，等一手14寸😋，等macos for arm再发展发展
